### ISSUE TITLE
How to use with Laravel

### ISSUE THREAD

**Issue by sarfraznawaz2005** [garygreen/disabler#2]
Hi,

I tried using with Laravel but I always get `$(...).disabler is not a function`. This is what I did:

 - `npm i disabler`
 - Added `window.disabler = require('disabler');`  in `app.js` file
 - Ran `npm run dev`
 - In my script, I have `$('input[type="submit"]').disabler();`

Thanks

**Comment by sarfraznawaz2005** [comment]
Can you at least tell me how I can fix this on my own if you don't plan to fix this? Thanks

**Comment by garygreen** [comment]
jQuery support was removed, so it's now just a standard dependency free ES6 plugin.

Here's how I'm using it in one of our projects:

**disabler.js**
```js
import Disabler from 'disabler';

function bindDisabler(form) {
    if (! form.querySelector('[data-disabler]')) {
        return;
    }

    form.addEventListener('submit', function(event) {
        var btns = form.querySelectorAll('[data-disabler]');
        btns.forEach(function(btn) {
            if (btn.disabler) {
                btn.disabler.debounce();
            } else {
                btn.disabler = new Disabler(btn, {
                    auto: true, // This will automatically disable the button, straight away
                    html: function() {
                        return '<i class="fa fa-circle-o-notch fa-spin mr-2"></i> ' + btn.dataset.disabler
                    }
                });
            }
        });
    });
}

export default bindDisabler;
```

**main.js**
```js
import bindDisabler from './disabler';

document.querySelectorAll('form').forEach(function(form) {
	bindDisabler(form);
});
```

It really depends on how you intend to use it, but in our case we have a form with a `<button data-disabler>` on it, and it will disable the button on click, re-enable it after the default timeout. The reason we only initialise after we've submitted the form is because then we can allow any native HTML validations (e.g. `required` `min` etc) to fire and not cause disabler to run - as the submit event would only fire if the form is validated.

This maybe different to whatever implementation you need, but in it's most basic form:

```js
import Disabler from 'disabler';
var disabler = new Disabler(document.querySelector('button')); // This will disable the button on click.
```

It's left as an exercise up to the user of this plugin when they want to initialise/bind the disabler.

Also, if you use something like Vue js or React, it's probably not worth the effort in using this plugin - you can easily disable/enable buttons depending on state.

**Comment by sarfraznawaz2005** [comment]
Awesome, thanks for the reply it helps :)

**Comment by sarfraznawaz2005** [comment]
I also created my own version inspired from your work :)

https://github.com/sarfraznawaz2005/buttondisabler
